name: CI

on: 
  workflow_dispatch:

jobs:
  build-binary:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build binary
      run: |
        docker run --rm -v ${PWD}:/project roblkyogre/moonlight3dsbuilder make dist
    - uses: actions/upload-artifact@v2
      with:
       name: moonlight-3ds
       path: dist/*
